export const LOADING = 'LOADING';
export const ERROR = 'ERROR';
export const GET_WEATHER_DATA = 'GET_WEATHER_DATA';
export const SEARCH_MOVIE_START = 'SEARCH_MOVIE_START';
export const SEARCH_MOVIE_ERROR = 'SEARCH_MOVIE_ERROR';
export const SEARCH_MOVIE_COMPLETE = 'SEARCH_MOVIE_COMPLETE';
export const KEY = '3c566bde';
export const SET_VALUE_SEARCH = 'SET_VALUE_SEARCH';